import {
  Bot,
  Gavel,
  MessagesSquare,
  Info,
  Image,
  Sparkles,
  Newspaper,
  HelpCircle,
  Link2,
  Link as Link1,
  FilterIcon,
  Video,
  MessageSquare,
  PlayCircle,
  Target,
  MapPinned,
  Map as MapIcon,
  Menu,
  Star,
  BarChartHorizontal,
  Presentation,
  Search,
  BookOpen,
  Plus,
  MapPin,
  Calendar,
  Eye,
  Book,
  Telescope,
  Briefcase,
  Brain,
  Radio,
  Store,
  Twitter,
  TriangleAlertIcon,
  MessageSquareWarning,
  Globe,
  Megaphone,
  ShieldQuestion,
} from 'lucide-react';
import { IFeaturedIcon } from '@/types';

const featureIcons: Record<string, IFeaturedIcon> = {
  ai_overview: {
    icon: Bot,
    label: 'AI Overview',
    bgClass: 'bg-blue-100 dark:bg-blue-900',
    textClass: 'text-blue-800 dark:text-blue-200',
    borderClass: 'border-blue-200 dark:border-blue-800',
  },
  ad_results: {
    icon: BarChartHorizontal,
    label: 'Ad Results',
    bgClass: 'bg-green-100 dark:bg-green-900',
    textClass: 'text-green-800 dark:text-green-200',
    borderClass: 'border-green-200 dark:border-green-800',
  },
  answer_box: {
    icon: TriangleAlertIcon,
    label: 'Answer Box',
    bgClass: 'bg-red-100 dark:bg-red-900',
    textClass: 'text-red-800 dark:text-red-200',
    borderClass: 'border-red-200 dark:border-red-800',
  },
  available_on: {
    icon: Presentation,
    label: 'Available On',
    bgClass: 'bg-yellow-100 dark:bg-yellow-900',
    textClass: 'text-yellow-800 dark:text-yellow-200',
    borderClass: 'border-yellow-200 dark:border-yellow-800',
  },
  broaden_searches: {
    icon: Search,
    label: 'Broaden Searches',
    bgClass: 'bg-purple-100 dark:bg-purple-900',
    textClass: 'text-purple-800 dark:text-purple-200',
    borderClass: 'border-purple-200 dark:border-purple-800',
  },
  buying_guide: {
    icon: BookOpen,
    label: 'Buying Guide',
    bgClass: 'bg-indigo-100 dark:bg-indigo-900',
    textClass: 'text-indigo-800 dark:text-indigo-200',
    borderClass: 'border-indigo-200 dark:border-indigo-800',
  },
  complementary_results: {
    icon: Plus,
    label: 'Complementary Results',
    bgClass: 'bg-gray-100 dark:bg-gray-900',
    textClass: 'text-gray-800 dark:text-gray-200',
    borderClass: 'border-gray-200 dark:border-gray-800',
  },
  dmca_messages: {
    icon: Gavel,
    label: 'DMCA Messages',
    bgClass: 'bg-red-100 dark:bg-red-900',
    textClass: 'text-red-800 dark:text-red-200',
    borderClass: 'border-red-200 dark:border-red-800',
  },
  discover_more_places: {
    icon: MapPin,
    label: 'Discover More Places',
    bgClass: 'bg-teal-100 dark:bg-teal-900',
    textClass: 'text-teal-800 dark:text-teal-200',
    borderClass: 'border-teal-200 dark:border-teal-800',
  },
  discussions_forums: {
    icon: MessagesSquare,
    label: 'Discussions and Forums',
    bgClass: 'bg-cyan-100 dark:bg-cyan-900',
    textClass: 'text-cyan-800 dark:text-cyan-200',
    borderClass: 'border-cyan-200 dark:border-cyan-800',
  },
  events_results: {
    icon: Calendar,
    label: 'Events Results',
    bgClass: 'bg-orange-100 dark:bg-orange-900',
    textClass: 'text-orange-800 dark:text-orange-200',
    borderClass: 'border-orange-200 dark:border-orange-800',
  },
  google_about_this_result: {
    icon: Info,
    label: 'Google About This Result API',
    bgClass: 'bg-gray-100 dark:bg-gray-900',
    textClass: 'text-gray-800 dark:text-gray-200',
    borderClass: 'border-gray-200 dark:border-gray-800',
  },
  google_ads_transparency: {
    icon: Eye,
    label: 'Google Ads Transparency API',
    bgClass: 'bg-blue-100 dark:bg-blue-900',
    textClass: 'text-blue-800 dark:text-blue-200',
    borderClass: 'border-blue-200 dark:border-blue-800',
  },
  grammar_check: {
    icon: Book,
    label: 'Grammar Check',
    bgClass: 'bg-yellow-100 dark:bg-yellow-900',
    textClass: 'text-yellow-800 dark:text-yellow-200',
    borderClass: 'border-yellow-200 dark:border-yellow-800',
  },
  immersive_products: {
    icon: Telescope,
    label: 'Immersive Products',
    bgClass: 'bg-indigo-100 dark:bg-indigo-900',
    textClass: 'text-indigo-800 dark:text-indigo-200',
    borderClass: 'border-indigo-200 dark:border-indigo-800',
  },
  inline_images: {
    icon: Image,
    label: 'Inline Images',
    bgClass: 'bg-green-100 dark:bg-green-900',
    textClass: 'text-green-800 dark:text-green-200',
    borderClass: 'border-green-200 dark:border-green-800',
  },
  jobs_results: {
    icon: Briefcase,
    label: 'Jobs Results',
    bgClass: 'bg-purple-100 dark:bg-purple-900',
    textClass: 'text-purple-800 dark:text-purple-200',
    borderClass: 'border-purple-200 dark:border-purple-800',
  },
  knowledge_graph: {
    icon: Brain,
    label: 'Knowledge Graph',
    bgClass: 'bg-teal-100 dark:bg-teal-900',
    textClass: 'text-teal-800 dark:text-teal-200',
    borderClass: 'border-teal-200 dark:border-teal-800',
  },
  latest_posts: {
    icon: Sparkles,
    label: 'Latest Posts',
    bgClass: 'bg-pink-100 dark:bg-pink-900',
    textClass: 'text-pink-800 dark:text-pink-200',
    borderClass: 'border-pink-200 dark:border-pink-800',
  },
  local_news: {
    icon: Radio,
    label: 'Local News',
    bgClass: 'bg-red-100 dark:bg-red-900',
    textClass: 'text-red-800 dark:text-red-200',
    borderClass: 'border-red-200 dark:border-red-800',
  },
  map_results: {
    icon: Map,
    label: 'Local Pack',
    bgClass: 'bg-green-100 dark:bg-green-900',
    textClass: 'text-green-800 dark:text-green-200',
    borderClass: 'border-green-200 dark:border-green-800',
  },
  news_results: {
    icon: Newspaper,
    label: 'News Results',
    bgClass: 'bg-blue-100 dark:bg-blue-900',
    textClass: 'text-blue-800 dark:text-blue-200',
    borderClass: 'border-blue-200 dark:border-blue-800',
  },
  product_results: {
    icon: Store,
    label: 'Product Results',
    bgClass: 'bg-gray-100 dark:bg-gray-900',
    textClass: 'text-gray-800 dark:text-gray-200',
    borderClass: 'border-gray-200 dark:border-gray-800',
  },
  twitter_results: {
    icon: Twitter,
    label: 'Twitter Results',
    bgClass: 'bg-blue-100 dark:bg-blue-900',
    textClass: 'text-blue-800 dark:text-blue-200',
    borderClass: 'border-blue-200 dark:border-blue-800',
  },
  search_information: {
    icon: Info,
    label: 'Search Information',
    bgClass: 'bg-blue-100 dark:bg-blue-900',
    textClass: 'text-blue-800 dark:text-blue-200',
    borderClass: 'border-blue-200 dark:border-blue-800',
  },

  related_questions: {
    icon: HelpCircle,
    label: 'Related Questions',
    bgClass: 'bg-orange-100 dark:bg-orange-900',
    textClass: 'text-orange-800 dark:text-orange-200',
    borderClass: 'border-orange-200 dark:border-orange-800',
  },
  top_stories: {
    icon: Newspaper,
    label: 'Top Stories',
    bgClass: 'bg-red-100 dark:bg-red-900',
    textClass: 'text-red-800 dark:text-red-200',
    borderClass: 'border-red-200 dark:border-red-800',
  },
  top_stories_link: {
    icon: Link2,
    label: 'Top Stories Link',
    bgClass: 'bg-indigo-100 dark:bg-indigo-900',
    textClass: 'text-indigo-800 dark:text-indigo-200',
    borderClass: 'border-indigo-200 dark:border-indigo-800',
  },
  top_stories_serpapi_link: {
    icon: Link1,
    label: 'Top Stories SERP Link',
    bgClass: 'bg-pink-100 dark:bg-pink-900',
    textClass: 'text-pink-800 dark:text-pink-200',
    borderClass: 'border-pink-200 dark:border-pink-800',
  },
  related_searches: {
    icon: Sparkles,
    label: 'Related Searches',
    bgClass: 'bg-cyan-100 dark:bg-cyan-900',
    textClass: 'text-cyan-800 dark:text-cyan-200',
    borderClass: 'border-cyan-200 dark:border-cyan-800',
  },
  filters: {
    icon: FilterIcon,
    label: 'Filters',
    bgClass: 'bg-cyan-100 dark:bg-yellow-900',
    textClass: 'text-cyan-800 dark:text-cyan-200',
    borderClass: 'border-cyan-200 dark:border-cyan-800',
  },
  inline_videos: {
    icon: Video,
    label: 'Inline Videos',
    bgClass: 'bg-yellow-100 dark:bg-yellow-900',
    textClass: 'text-yellow-800 dark:text-yellow-200',
    borderClass: 'border-yellow-200 dark:border-yellow-800',
  },
  perspectives: {
    icon: MessageSquare,
    label: 'Perspectives',
    bgClass: 'bg-violet-100 dark:bg-violet-900',
    textClass: 'text-violet-800 dark:text-violet-200',
    borderClass: 'border-violet-200 dark:border-violet-800',
  },
  discussions_and_forums: {
    icon: MessagesSquare,
    label: 'Discussions & Forums',
    bgClass: 'bg-fuchsia-100 dark:bg-fuchsia-900',
    textClass: 'text-fuchsia-800 dark:text-fuchsia-200',
    borderClass: 'border-fuchsia-200 dark:border-fuchsia-800',
  },
  short_videos: {
    icon: PlayCircle,
    label: 'Short Videos',
    bgClass: 'bg-rose-100 dark:bg-rose-900',
    textClass: 'text-rose-800 dark:text-rose-200',
    borderClass: 'border-rose-200 dark:border-rose-800',
  },
  ads: {
    icon: Target,
    label: 'Ads',
    bgClass: 'bg-lime-100 dark:bg-lime-900',
    textClass: 'text-lime-800 dark:text-lime-200',
    borderClass: 'border-lime-200 dark:border-lime-800',
  },
  local_map: {
    icon: MapPinned,
    label: 'Local Map',
    bgClass: 'bg-gray-100 dark:bg-gray-900',
    textClass: 'text-teal-800 dark:text-teal-200',
    borderClass: 'border-teal-200 dark:border-teal-800',
  },
  local_results: {
    icon: MapIcon,
    label: 'Local Results',
    bgClass: 'bg-emerald-100 dark:bg-emerald-900',
    textClass: 'text-emerald-800 dark:text-emerald-200',
    borderClass: 'border-emerald-200 dark:border-emerald-800',
  },
  menu_highlights: {
    icon: Menu,
    label: 'Menu Highlights',
    bgClass: 'bg-amber-100 dark:bg-amber-900',
    textClass: 'text-amber-800 dark:text-amber-200',
    borderClass: 'border-amber-200 dark:border-amber-800',
  },
  reviews: {
    icon: Star,
    label: 'Reviews',
    bgClass: 'bg-orange-100 dark:bg-orange-900',
    textClass: 'text-orange-800 dark:text-orange-200',
    borderClass: 'border-orange-200 dark:border-orange-800',
  },
  answer_box_list: {
    icon: MessageSquareWarning,
    label: 'Answer Box List',
    bgClass: 'bg-red-100 dark:bg-red-900',
    textClass: 'text-red-800 dark:text-red-200',
    borderClass: 'border-red-200 dark:border-red-800',
  },
  places_sites: {
    icon: Globe,
    label: 'Places sites',
    bgClass: 'bg-red-100 dark:bg-red-900',
    textClass: 'text-red-800 dark:text-red-200',
    borderClass: 'border-red-200 dark:border-red-800',
  },
  local_ads: {
    icon: Megaphone,
    label: 'Local Ads',
    bgClass: 'bg-amber-100 dark:bg-amber-900',
    textClass: 'text-amber-800 dark:text-amber-200',
    borderClass: 'border-amber-200 dark:border-amber-800',
  },
  questions_and_answers: {
    icon: ShieldQuestion,
    label: 'Questions and Answers',
    bgClass: 'bg-lime-100 dark:bg-lime-900',
    textClass: 'text-lime-800 dark:text-lime-200',
    borderClass: 'border-lime-200 dark:border-lime-800',
  },
};

export default featureIcons;
