export const LOCATIONS_MAP = {
  'Los Angeles': 'LA',
  California: 'CA',
  'United States': 'US',
  Tempe: 'Tempe',
  Arizona: 'AZ',
  'San Mateo': 'San M.',
  Houston: 'Hou',
  Texas: 'TX',
  Chicago: 'CHI',
  Illinois: 'IL',
  Brooklyn: 'BK',
  'New York': 'NY',
  'Las Vegas': 'LV',
  Nevada: 'NV',
  'San Antonio': 'SA',
};
